(source gnu)
(source melpa)
(source marmalade)

(depends-on "zenburn-theme")
(depends-on "magit")
(depends-on "flycheck")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "jedi")
(depends-on "ace-jump-mode")
(depends-on "python-mode")
(depends-on "js2-mode")
(depends-on "php-mode")
(depends-on "yaml-mode")